# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Digitale Bewerbungsmappe - Frank Wünsch
email: wuensch.frank@web.de
description: >- # this means to ignore newlines until "baseurl:"
  Hier steht eine Beschreibung
  über mehrere Zeilen hinweg...
baseurl: "/DigitaleBewerbungsmappe" # the subpath of your site, e.g. /blog
url: "https://frankwuensch.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: FrankWuensch
menu_symbol: /src/symbols/menu.svg
certificates:
  - name: KUKA Programmieren 1
    institute: KUKA College Augsburg [2019]
    link: /src/certificates/KUKA_Programmieren_1.pdf
  - name: SPS Fachkraft
    institute: ILS Hamburg [2019-2020]
    link: /src/certificates/SPS_Fachkraft_ILS.pdf
  - name: Geprüfter C++ Programmierer
    institute: ILS Hamburg [2021-2022]
    link: /src/certificates/CPP_Programmierer_ILS.pdf
  - name: Python Programmierung Data Science / Machine Learning
    institute: ILS Hamburg [2023-2024]
    link: /src/certificates/Python_Programmierung_ILS.pdf
  - name: Hackathon Kirchheim
    institute: bwcon GmbH [2023]
    link: /src/certificates/Hackathon_Kirchheim.pdf
  - name: IHK Data Analyst
    institute: IHK Akademie Bayern [2025]
    link: /src/certificates/IHK_Data_Analyst_DSP.pdf

plugins:
  - jekyll-inline-svg

# Build settings

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
